[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "qemu-run"
publish = false
version = "0.1.0"

[dependencies]
anyhow = "1.0.32"
defmt-decoder = { path = "../decoder" }
defmt-elf2table = { path = "../elf2table" }
