[package]
authors = ["The Knurling-rs developers"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "qemu-run"
publish = false
version = "0.1.0"

[dependencies]
anyhow = "1"
defmt-decoder = { path = "../decoder", features = ["unstable"], version = "=0.3.0" }
