[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "defmt-semihosting"
publish = false
version = "0.1.0"

[dependencies]
defmt = { path = "../../defmt" }
cortex-m = "0.7.2"
cortex-m-semihosting = "0.3.7"
