on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  merge_group:

name: Check semver breakage

jobs:
  cargo-semver-check:
    runs-on: ubuntu-latest

    # Skip if PR is labelled as breaking change
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'breaking change') }}

    steps:
      - uses: actions/checkout@v4
      - name: Semver check host crates
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features
          manifest-path: defmt
      - name: Semver check host crates
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features
          manifest-path: defmt-03
      - name: Semver check host crates
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features
          manifest-path: decoder
      - name: Semver check host crates
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features
          manifest-path: decoder/defmt-json-schema
      - name: Semver check host crates
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features
          manifest-path: parser
      - name: Semver check firmware crates
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          manifest-path: firmware/
